on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9, '3.10']
    name: main
    steps:
      - uses: actions/checkout@v4
      - name: Install python version
        uses: gabrielfalcao/pyenv-action@v17
        with:
          default: ${{ matrix.python-version }}
          command: pip install -U pip tox<4
      - name: clean .coverage
        shell: bash
        run: find . -name .coverage -delete
      - name: Run tox with tox-gh-actions
        uses: tox
